# Generated by Django 3.1.4 on 2020-12-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateWiseTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('total_samples', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('positive', models.IntegerField()),
            ],
        ),
    ]
